// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DynamicalSystem struct {
	ID string `json:"id"`
}

type PetriDish struct {
	ID        string               `json:"id"`
	Ticks     int                  `json:"ticks"`
	System    *DynamicalSystem     `json:"system"`
	Snapshots []*PetriDishSnapshot `json:"snapshots"`
}

type PetriDishFrame struct {
	PetriDishID string `json:"petriDishID"`
	TickStamp   int    `json:"tickStamp"`
	Data        string `json:"data"`
}

type PetriDishSnapshot struct {
	PetriDishID string `json:"petriDishID"`
	TickStamp   int    `json:"tickStamp"`
	Image       string `json:"image"`
}
